/* ============================================================
   AAEA Quiz Bowl question bank
   Format: { y: year, c: category, v: point value, q: question, a: answer }
   Categories: Micro, Macro, Finance, RePo, Quant, Marketing, Management, Potpourri
   To add more questions, append lines in the same format anywhere in the array.
   Picture-dependent questions from the source docs are intentionally excluded.
   ============================================================ */
window.QUIZ_DATA = [

/* ---------------- 2016 ---------------- */
{y:2016,c:"Micro",v:5,q:"What two 'groups' do microeconomists try to predict behavior for?",a:"Consumers (or households) and firms"},
{y:2016,c:"Micro",v:10,q:"Judy loves Snickers bars. When Snickers go on sale, she buys more Snickers and fewer M&Ms (which she also loves). What 'effect' does Judy's behavior illustrate?",a:"The Substitution Effect"},
{y:2016,c:"Micro",v:15,q:"As the population of an area increases rapidly, what should happen to most prices?",a:"Prices should rise"},
{y:2016,c:"Micro",v:20,q:"What type of cost makes the 'short run' different than the 'long run'?",a:"In the short run there are fixed costs; everything is variable in the long run"},
{y:2016,c:"Micro",v:25,q:"For a firm in a perfectly competitive market, what is Marginal Revenue equal to?",a:"The market price"},
{y:2016,c:"Macro",v:5,q:"True or False: The only way the government can influence Aggregate Demand is through changes in its own purchases.",a:"False"},
{y:2016,c:"Macro",v:10,q:"Which of the following does not belong: Long Run Aggregate Supply, Potential Output, Natural Unemployment, Cyclical Unemployment?",a:"Cyclical unemployment"},
{y:2016,c:"Macro",v:15,q:"The ability to produce a good at a lower opportunity cost than another country is known as what?",a:"Comparative Advantage"},
{y:2016,c:"Macro",v:20,q:"______ income taxes soften the blow of unwanted (cyclical) unemployment.",a:"Progressive"},
{y:2016,c:"Macro",v:25,q:"Given a recessionary gap due to an adverse supply shock, how do classical economists assume the economy will passively improve?",a:"Newly unemployed workers will accept lower wages, increasing SRAS (output rises)"},
{y:2016,c:"Finance",v:5,q:"If assets exceed liabilities, a business entity has this.",a:"Positive equity"},
{y:2016,c:"Finance",v:10,q:"Define 'real property.'",a:"It is immovable, permanent, attached to the ground, or the ground itself"},
{y:2016,c:"Finance",v:15,q:"This accounting ratio compares sales revenue to the cost of goods sold.",a:"Gross margin"},
{y:2016,c:"Finance",v:20,q:"What does NASDAQ stand for?",a:"National Association of Securities Dealers Automated Quotations"},
{y:2016,c:"Finance",v:25,q:"Why is depreciation known as a 'non-cash' expense?",a:"It is an economic expense for which there is no actual payment"},
{y:2016,c:"RePo",v:5,q:"In environmental concerns, what does BMP stand for?",a:"Best Management Practice"},
{y:2016,c:"RePo",v:10,q:"Runoff pollutants with no explicit cause are what type of pollution?",a:"Non-point pollution"},
{y:2016,c:"RePo",v:15,q:"In the absence of externalities, what allocates resources most effectively, according to most economists?",a:"The market system"},
{y:2016,c:"RePo",v:20,q:"Land is available for sale to two farmers. Both use the same cost/benefit analysis process; one buys and the other declines. What single factor is different between their analyses?",a:"The discount rate"},
{y:2016,c:"RePo",v:25,q:"The Maastricht Treaty of 1992 created what?",a:"The European Union"},
{y:2016,c:"Quant",v:5,q:"What is the qualitative description of Pi, as used in geometry?",a:"The ratio of the circumference to the diameter of any circle"},
{y:2016,c:"Quant",v:10,q:"What is the name for the following: (3, 4, 5) (5, 12, 13) (8, 15, 17) (7, 24, 25)?",a:"Pythagorean Triples"},
{y:2016,c:"Quant",v:15,q:"What does BLUE stand for?",a:"Best Linear Unbiased Estimator"},
{y:2016,c:"Quant",v:20,q:"What is another name for a Gaussian distribution?",a:"Normal distribution"},
{y:2016,c:"Quant",v:25,q:"If a matrix does not have an inverse, what is it called?",a:"Singular"},
{y:2016,c:"Marketing",v:5,q:"What does AMA stand for?",a:"American Marketing Association"},
{y:2016,c:"Marketing",v:10,q:"__________ is the idea that socially responsible companies will outperform their peers by focusing on the world's social problems and viewing them as opportunities to build profit and help the world at the same time.",a:"Sustainability"},
{y:2016,c:"Marketing",v:15,q:"Ralph was happy with his newly purchased $1200 laptop. After removing it from the box he saw an ad for a similar laptop for $1100 and suddenly felt sick to his stomach. What was he likely experiencing?",a:"Cognitive Dissonance"},
{y:2016,c:"Marketing",v:20,q:"What animal describes a trader who thinks prices will increase?",a:"Bull"},
{y:2016,c:"Marketing",v:25,q:"What is the AMA's definition of Marketing?",a:"Creating, communicating, delivering, and exchanging offerings that have value for customers, clients, partners, and society at large"},
{y:2016,c:"Management",v:5,q:"Workers joining together and refusing to work because of a labor disagreement are doing what?",a:"Striking"},
{y:2016,c:"Management",v:10,q:"What line are workers crossing when they go back to work before an agreement is made and others continue to strike?",a:"A picket line"},
{y:2016,c:"Management",v:15,q:"What is a firm doing when it allows its intellectual property to be used in exchange for payment?",a:"Licensing"},
{y:2016,c:"Management",v:20,q:"What does the acronym SMART stand for?",a:"Specific, Measurable, Achievable, Realistic, Time-based"},
{y:2016,c:"Management",v:25,q:"What is the term for a large compensation package given to an executive when they are let go (fired)?",a:"Golden Parachute"},
{y:2016,c:"Potpourri",v:5,q:"This Celtic legend is also known as 'The Hick from French Lick.'",a:"Larry Bird"},
{y:2016,c:"Potpourri",v:10,q:"What year did the American Revolutionary War begin?",a:"1775"},
{y:2016,c:"Potpourri",v:15,q:"What is the official name of Massachusetts?",a:"The Commonwealth of Massachusetts"},
{y:2016,c:"Potpourri",v:20,q:"Lyndon Johnson leaked that John F. Kennedy suffered from what disease during the 1960 presidential campaign?",a:"Addison's Disease"},
{y:2016,c:"Potpourri",v:25,q:"Name 6 of the 8 Ivy League schools.",a:"Cornell, Dartmouth, Harvard, Brown, Yale, Columbia, Princeton, Penn"},

/* ---------------- 2017 ---------------- */
{y:2017,c:"Micro",v:5,q:"The ____________ states that price and quantity are inversely related, ceteris paribus.",a:"Law of demand"},
{y:2017,c:"Micro",v:10,q:"In perfect competition, MR is represented by a _____________ line.",a:"Horizontal"},
{y:2017,c:"Micro",v:15,q:"The ______________ is defined as the locus of those cost-minimizing input combinations at various levels of production (when input prices are constant).",a:"Expansion Path"},
{y:2017,c:"Micro",v:20,q:"Movie theaters conduct what type of price discrimination?",a:"Type III (third-degree): different prices to different groups"},
{y:2017,c:"Micro",v:25,q:"Market structures are categorized mainly by which two criteria?",a:"The number of firms (producers) and product differentiation (barriers to entry acceptable)"},
{y:2017,c:"Macro",v:5,q:"The spending on final goods and services by households is ________.",a:"Consumption (C)"},
{y:2017,c:"Macro",v:10,q:"In the so-called 'base year,' what is the relationship between nominal GDP and real GDP?",a:"They are equal"},
{y:2017,c:"Macro",v:15,q:"In Keynesian macroeconomics, what is assumed about prices?",a:"They are 'sticky' in the short run (slow to adjust)"},
{y:2017,c:"Macro",v:20,q:"When the level of output in an economy falls below full-employment output, what is known about the unemployment rate?",a:"It exceeds the natural rate of unemployment"},
{y:2017,c:"Macro",v:25,q:"Unemployment due to a mismatch between job seekers and available jobs, either in skills or geography, is classified as what type of unemployment?",a:"Structural unemployment"},
{y:2017,c:"Finance",v:5,q:"___________ is a mix of assets, enterprises, or investments.",a:"Portfolio"},
{y:2017,c:"Finance",v:10,q:"Sarah will receive a $5,000 bonus one year from now. The process of determining how much that bonus is worth today is called ____________.",a:"Discounting"},
{y:2017,c:"Finance",v:15,q:"Name the four financial statements commonly used to assess the position and progress of the farm business.",a:"Balance sheet; income statement; statement of retained earnings (equity statement); statement of cash flows"},
{y:2017,c:"Finance",v:20,q:"SS-AAEA, Inc. is financed with 60% debt and 40% equity. This mixture of debt and equity is referred to as the firm's ________.",a:"Capital structure"},
{y:2017,c:"Finance",v:25,q:"Sarah is analyzing a proposed project to determine how changes in the variable costs per unit would affect the project's NPV. Sarah is conducting a ____________ analysis.",a:"Sensitivity analysis"},
{y:2017,c:"RePo",v:5,q:"A tax on imports is called a ________.",a:"Tariff"},
{y:2017,c:"RePo",v:10,q:"What is a net loss in total surplus called?",a:"Deadweight loss"},
{y:2017,c:"RePo",v:15,q:"What type of good is non-excludable, but rival?",a:"Common resource"},
{y:2017,c:"RePo",v:20,q:"What two properties are necessary for the Coase Theorem to work?",a:"Low transaction costs and well-defined property rights"},
{y:2017,c:"RePo",v:25,q:"Name two western European countries that are currently NOT members of the European Union.",a:"Any two of: Iceland, Norway, Switzerland, Andorra, Monaco, San Marino, Liechtenstein"},
{y:2017,c:"Quant",v:5,q:"The slope of a horizontal line equals __________.",a:"Zero"},
{y:2017,c:"Quant",v:10,q:"Data collected at the same or approximately the same time are called __________.",a:"Cross-sectional data"},
{y:2017,c:"Quant",v:15,q:"The intersection of the sets (0, 2, 4) and (2, 6, 8) is _______.",a:"The set {2}"},
{y:2017,c:"Quant",v:20,q:"If the correlation coefficient is -1, then in an XY graph the two variables move in _____________ direction(s).",a:"Exactly opposite directions"},
{y:2017,c:"Quant",v:25,q:"This functional form is widely used to represent a production function.",a:"Cobb-Douglas (quadratic also accepted)"},
{y:2017,c:"Marketing",v:5,q:"TQM stands for what?",a:"Total Quality Management"},
{y:2017,c:"Marketing",v:10,q:"This term refers to the pattern of shared values and beliefs that influences employee attitudes and behavior.",a:"Organizational (company) culture"},
{y:2017,c:"Marketing",v:15,q:"____________ is the process that buyers and sellers use to determine whether a marketing exchange will be beneficial.",a:"Valuation"},
{y:2017,c:"Marketing",v:20,q:"The number of contracts or commitments outstanding in futures and options that are trading on an official exchange at any one time is called what?",a:"Open interest"},
{y:2017,c:"Marketing",v:25,q:"A comprehensive review of an organization's marketing strategies, tactics, and performance is called ________.",a:"Marketing Audit"},
{y:2017,c:"Management",v:5,q:"The acronym 'SMART' refers to qualities of good goals and objectives. What does 'SMART' stand for?",a:"Specific, Measurable, Attainable (Achievable), Realistic, Time-oriented (Timely)"},
{y:2017,c:"Management",v:10,q:"Which of the following would not appear on a cash flow budget: feed purchases, inventory changes, family living expenses, or cost of a new tractor?",a:"Inventory changes"},
{y:2017,c:"Management",v:15,q:"What type of budget examines only one operation of a farm or ranch business?",a:"An enterprise budget"},
{y:2017,c:"Management",v:20,q:"What type of costs are not considered when making a short-run production decision?",a:"Fixed costs"},
{y:2017,c:"Management",v:25,q:"In inventory management, 'EOQ' is the cost-minimizing ________.",a:"Order size (Economic Order Quantity)"},
{y:2017,c:"Potpourri",v:5,q:"Give a nickname for Chicago.",a:"The Windy City (also: City of Big Shoulders, The Second City, The City that Works)"},
{y:2017,c:"Potpourri",v:10,q:"Who is the goddess of grain, agriculture, harvest, growth, and nourishment in Greek mythology?",a:"Demeter"},
{y:2017,c:"Potpourri",v:15,q:"With the acquisition of this company, Amazon may change the landscape of the grocery industry.",a:"Whole Foods"},
{y:2017,c:"Potpourri",v:20,q:"Name the four states that are visible from the top of the Willis Tower.",a:"Indiana, Illinois, Michigan, Wisconsin"},
{y:2017,c:"Potpourri",v:25,q:"This Muppets TV program star is getting a new voice.",a:"Kermit the Frog"},

/* ---------------- 2018 ---------------- */
{y:2018,c:"Micro",v:5,q:"The value of your next best alternative when making a decision is often called the _____ _____ of the decision.",a:"Opportunity cost"},
{y:2018,c:"Micro",v:10,q:"One of the most important lessons of economics is that _____ matter because they motivate our behavior.",a:"Incentives"},
{y:2018,c:"Micro",v:15,q:"What is likely to happen to enrollment at colleges and universities during a recession?",a:"Enrollment is likely to increase"},
{y:2018,c:"Micro",v:20,q:"Katie works at a customer service center and every hour she has a choice between answering 20 phone calls or responding to 40 emails. What is Katie's opportunity cost of answering one phone call?",a:"Responding to 2 emails"},
{y:2018,c:"Micro",v:25,q:"A graph that shows all of the consumption bundles that a consumer can afford given their income is called a what?",a:"Budget constraint"},
{y:2018,c:"Macro",v:5,q:"The branch of economics that studies the economy as a whole is called what?",a:"Macroeconomics"},
{y:2018,c:"Macro",v:10,q:"The market value of all final goods and services produced within a country in a given time period is the definition of what?",a:"Gross Domestic Product (GDP)"},
{y:2018,c:"Macro",v:15,q:"Which index is used to calculate the official inflation rate for the United States?",a:"Consumer Price Index (CPI)"},
{y:2018,c:"Macro",v:20,q:"What is true about the relationship between Real GDP and Full-Employment Output if a recessionary gap is present?",a:"Real GDP < Full-Employment Output"},
{y:2018,c:"Macro",v:25,q:"Suppose 2010 is the 'base year.' The GDP Deflator for 2018 equals 112.5. How do we interpret this number?",a:"The price level in 2018 is 12.5% higher than in 2010"},
{y:2018,c:"Finance",v:5,q:"SWOT stands for _________.",a:"Strengths, Weaknesses, Opportunities, Threats"},
{y:2018,c:"Finance",v:10,q:"Common-size financial statements present all balance sheet account values as a percentage of _________.",a:"Total assets"},
{y:2018,c:"Finance",v:15,q:"The average net income of a project divided by the project's average book value is referred to as the project's _________.",a:"Average accounting return"},
{y:2018,c:"Finance",v:20,q:"Which one of the following will decrease the liquidity level of a firm: cash sale of inventory, cash purchase of inventory, collection of an account receivable, or proceeds from a long-term loan?",a:"Cash purchase of inventory"},
{y:2018,c:"Finance",v:25,q:"A junk bond that was originally issued with a bond rating of AA is called a _____________.",a:"Fallen angel"},
{y:2018,c:"RePo",v:5,q:"The endowment of land and other resources including air, water, soil, forests, etc. comprise our _____ _____.",a:"Natural resources"},
{y:2018,c:"RePo",v:10,q:"A _____ allocation of a resource maximizes the net social benefits created by the resource's use.",a:"Efficient"},
{y:2018,c:"RePo",v:15,q:"What two important assumptions underlie the Coase Theorem?",a:"Property rights are well-defined and there are no transaction costs"},
{y:2018,c:"RePo",v:20,q:"All things equal, when a negative externality is present in a market, the socially optimal price is _____ than the market equilibrium price.",a:"Greater"},
{y:2018,c:"RePo",v:25,q:"Define the economic reserves of a natural resource.",a:"The quantity of a resource that can be extracted profitably based on current prices and technology"},
{y:2018,c:"Quant",v:5,q:"How many zeroes are there in a trillion?",a:"12"},
{y:2018,c:"Quant",v:10,q:"Suppose that y = ln(5x). What is the first derivative?",a:"1/x"},
{y:2018,c:"Quant",v:15,q:"Suppose that a function is concave at a particular point. What is known about the second derivative of the function at that point?",a:"It must be negative"},
{y:2018,c:"Quant",v:20,q:"What problem is said to exist in a regression model if the error terms do not have a constant variance?",a:"Heteroskedasticity"},
{y:2018,c:"Quant",v:25,q:"Suppose that x is a continuous random variable. What is the probability that x is exactly equal to a specific value, say X1?",a:"0"},
{y:2018,c:"Marketing",v:5,q:"A _____ consists of people with both the desire and the ability to buy a specific offering.",a:"Market"},
{y:2018,c:"Marketing",v:10,q:"What are the four elements of the marketing mix?",a:"Product, Price, Promotion, Place"},
{y:2018,c:"Marketing",v:15,q:"The benefits that an organization promises its customers to satisfy their needs make up the organization's _____ _____.",a:"Value proposition"},
{y:2018,c:"Marketing",v:20,q:"The social, economic, technological, competitive, and regulatory forces that are uncontrollable and affect marketing decisions are part of an organization's _____.",a:"Environment"},
{y:2018,c:"Marketing",v:25,q:"The benefits or customer value received by users of a product is also known as ___.",a:"Utility"},
{y:2018,c:"Management",v:5,q:"_____ is the set of activities directed at the efficient and effective use of resources in the pursuit of one or more goals.",a:"Management"},
{y:2018,c:"Management",v:10,q:"Which level of managers in a large organization is responsible for developing organizational goals and strategy?",a:"Upper-level (top-level) managers"},
{y:2018,c:"Management",v:15,q:"_____ means operating in such a way that resources are not wasted.",a:"Efficiency"},
{y:2018,c:"Management",v:20,q:"The idea that managers should not spend time on management areas that are progressing according to plan is known as what?",a:"Management by Exception"},
{y:2018,c:"Management",v:25,q:"The Classical school of management includes what two distinct schools of thought?",a:"Scientific management and Administrative management"},
{y:2018,c:"Potpourri",v:5,q:"Which President never lived in the White House?",a:"George Washington"},
{y:2018,c:"Potpourri",v:10,q:"Which state had the highest cash receipts from all agricultural products in 2016?",a:"California"},
{y:2018,c:"Potpourri",v:15,q:"Whose estate was taken over by the Union and eventually became Arlington National Cemetery?",a:"Robert E. Lee"},
{y:2018,c:"Potpourri",v:20,q:"What chapter of the Internal Revenue Code deals specifically with farm bankruptcy?",a:"Chapter 12"},
{y:2018,c:"Potpourri",v:25,q:"Which President died in the Capitol Building?",a:"John Quincy Adams"},

/* ---------------- 2019 ---------------- */
{y:2019,c:"Micro",v:5,q:"This occurs when a firm sells the same product at different prices to different customers.",a:"Price discrimination"},
{y:2019,c:"Micro",v:10,q:"State the law of demand.",a:"As the price of a good or service increases, its quantity demanded decreases (and vice versa)"},
{y:2019,c:"Micro",v:15,q:"What happens to the market price when demand is perfectly elastic and supply increases?",a:"The price does not change"},
{y:2019,c:"Micro",v:20,q:"What is the economic concept that suggests the proportion of income spent on food will decline as a consumer's income rises?",a:"Engel's Law"},
{y:2019,c:"Micro",v:25,q:"The slope of an isoquant is called what?",a:"Marginal Rate of Technical Substitution (MRTS)"},
{y:2019,c:"Macro",v:5,q:"The tax paid on an additional dollar of income is the what?",a:"Marginal tax rate"},
{y:2019,c:"Macro",v:10,q:"What are the three functions of money?",a:"Medium of exchange; unit of account; store of value"},
{y:2019,c:"Macro",v:15,q:"If the economy is experiencing an increase in the number of discouraged workers, what happens to the unemployment rate?",a:"It decreases"},
{y:2019,c:"Macro",v:20,q:"If the reserve ratio is 25%, what amount of excess reserves does a bank acquire when a business deposits a $10,000 check drawn on another bank?",a:"$7,500"},
{y:2019,c:"Macro",v:25,q:"Where are we in 'general equilibrium' in the IS-LM diagram?",a:"Only at the intersection of the IS and LM curves"},
{y:2019,c:"Finance",v:5,q:"The financial statement that provides a 'snapshot' of the firm's financial condition at a given point in time is the _____.",a:"Balance Sheet"},
{y:2019,c:"Finance",v:10,q:"What type of bankruptcy is specific to farmers?",a:"Chapter 12"},
{y:2019,c:"Finance",v:15,q:"What are intangible assets that represent the excess over book value paid for acquisitions?",a:"Goodwill"},
{y:2019,c:"Finance",v:20,q:"All else being equal, what is the impact of a shorter time to expiration on the value of an option?",a:"It decreases the value"},
{y:2019,c:"Finance",v:25,q:"What is the present value of a $2,000 ordinary annuity that earns 8% annually for an infinite number of periods?",a:"$25,000"},
{y:2019,c:"RePo",v:5,q:"The acronym USDA ERS stands for what?",a:"United States Department of Agriculture, Economic Research Service"},
{y:2019,c:"RePo",v:10,q:"Which U.S. president oversaw the Egypt-Israel peace agreement?",a:"Jimmy Carter"},
{y:2019,c:"RePo",v:15,q:"After reading which novel (written by Upton Sinclair) did President Roosevelt order an investigation into the meat industry?",a:"The Jungle"},
{y:2019,c:"RePo",v:20,q:"The _____ is a hypothesized relationship between various indicators of environmental degradation and income per capita.",a:"Environmental Kuznets Curve"},
{y:2019,c:"RePo",v:25,q:"What is a model of time lags between supply and demand, in which naive expectations on the part of suppliers lead to continual price oscillations, known as?",a:"Cobweb model"},
{y:2019,c:"Quant",v:5,q:"How many zeros are there in a quintillion?",a:"18"},
{y:2019,c:"Quant",v:10,q:"Suppose that y = ln(7x). What is the first derivative of y?",a:"1/x"},
{y:2019,c:"Quant",v:15,q:"If the dependent variable in a regression analysis is a dummy (binary, zero-one) variable, the econometrician would opt for a ____________ model.",a:"Logit or probit"},
{y:2019,c:"Quant",v:20,q:"If, for a fraction, the numerator is larger than the denominator, what can be said about its magnitude?",a:"It is larger than one"},
{y:2019,c:"Quant",v:25,q:"For a production function where TP = 60K\u00b2 \u2212 K\u00b3, give the respective equations for average product and marginal product.",a:"AP = 60K \u2212 K\u00b2; MP = 120K \u2212 3K\u00b2"},
{y:2019,c:"Marketing",v:5,q:"State the four characteristics of the perfectly competitive market structure.",a:"Many buyers & sellers, homogeneous product, zero barriers to entry, and perfect information"},
{y:2019,c:"Marketing",v:10,q:"How does the four-firm concentration ratio measure industry concentration?",a:"It measures the percent of sales accounted for by the four largest firms"},
{y:2019,c:"Marketing",v:15,q:"Consider three markets for the same good: a monopoly, a monopsony, and perfect competition. In which market would you expect the highest and the lowest price?",a:"Highest in monopoly; lowest in monopsony"},
{y:2019,c:"Marketing",v:20,q:"In terms of wholesaling, what is the primary difference between merchants and brokers?",a:"Merchants take ownership of the product; brokers do not"},
{y:2019,c:"Marketing",v:25,q:"Under this type of contract, a food processor supplies a farmer with the animals, feed, and other inputs; the farmer raises the animal to the processor's specifications.",a:"Production contract"},
{y:2019,c:"Management",v:5,q:"This statement provides a short description of why a business exists.",a:"Mission Statement"},
{y:2019,c:"Management",v:10,q:"____ management involves all of the decisions related to day-to-day activities that a business must perform efficiently.",a:"Operational"},
{y:2019,c:"Management",v:15,q:"This process involves looking inside an organization, identifying strengths and weaknesses, and assessing the resources available to the organization.",a:"Internal scanning"},
{y:2019,c:"Management",v:20,q:"State the first step in the rational decision-making model.",a:"Identify and define the problem"},
{y:2019,c:"Management",v:25,q:"Define gross margin.",a:"Income above variable costs; revenue minus cost of goods sold"},
{y:2019,c:"Potpourri",v:5,q:"Who wrote 'An Inquiry into the Nature and Causes of the Wealth of Nations'?",a:"Adam Smith"},
{y:2019,c:"Potpourri",v:10,q:"What is the largest state east of the Mississippi River?",a:"Georgia"},
{y:2019,c:"Potpourri",v:15,q:"A five-point scale ranging from strongly disagree to strongly agree that measures customer satisfaction is an example of what type of scale?",a:"Likert scale"},
{y:2019,c:"Potpourri",v:20,q:"In the 1930s, Brazilian cargo ships docking at Mobile accidentally introduced colonies of what notorious pest to the U.S.?",a:"Fire ants"},
{y:2019,c:"Potpourri",v:25,q:"What is dropped from the town's tallest building on New Year's Eve in Tallapoosa, Georgia?",a:"Opossum"},

/* ---------------- 2020 ---------------- */
{y:2020,c:"Micro",v:5,q:"True or False: The demand curve will shift right if the price of the good decreases.",a:"False"},
{y:2020,c:"Micro",v:10,q:"When your income fell, you started drinking less milk. You consider milk a(n) _____ good.",a:"Normal"},
{y:2020,c:"Micro",v:15,q:"In the market for hamburgers, what will happen if the population rises and the price of beef falls?",a:"Price change is ambiguous; quantity increases"},
{y:2020,c:"Micro",v:20,q:"What types of goods are nonrival and nonexcludable?",a:"Public goods"},
{y:2020,c:"Micro",v:25,q:"If exponents alpha and beta in a Cobb-Douglas production function sum to 1, the function displays _______.",a:"Constant returns to scale"},
{y:2020,c:"Macro",v:5,q:"The Phillips Curve shows the relationship between the unemployment rate and _______________.",a:"The rate of inflation"},
{y:2020,c:"Macro",v:10,q:"A depression is when the national economy experiences a period of contraction lasting ___________.",a:"One year or longer"},
{y:2020,c:"Macro",v:15,q:"What is the largest component of the money supply (M1)?",a:"Demand deposits"},
{y:2020,c:"Macro",v:20,q:"What do we call the revenue raised by the government through the creation of money?",a:"Seigniorage (or the Inflation Tax)"},
{y:2020,c:"Macro",v:25,q:"What is the key assumption about prices in the short run in the Keynesian model?",a:"Prices are sticky"},
{y:2020,c:"Finance",v:5,q:"This statement shows the annual flow and timing of cash into and out of a business.",a:"Cash Flow Statement"},
{y:2020,c:"Finance",v:10,q:"An expense that has been incurred but not yet paid is called what?",a:"Account Payable"},
{y:2020,c:"Finance",v:15,q:"A capital budgeting method which computes the length of time required for the accumulated returns to equal the original investment is called what?",a:"Payback period (payback method)"},
{y:2020,c:"Finance",v:20,q:"Net worth, the debt-to-asset ratio, and the leverage ratio are all measures of: efficiency, liquidity, repayment capacity, or solvency?",a:"Solvency"},
{y:2020,c:"Finance",v:25,q:"____________ is the number of years required to recover the initial cost of an investment.",a:"Payback Period"},
{y:2020,c:"RePo",v:5,q:"The acronym SNAP stands for what?",a:"Supplemental Nutrition Assistance Program"},
{y:2020,c:"RePo",v:10,q:"Which president vetoed the Morrill Act?",a:"James Buchanan"},
{y:2020,c:"RePo",v:15,q:"The ___ Act allowed any American man or woman who was the head of a household and at least 21 years old to claim up to 160 acres of unappropriated land.",a:"Homestead Act"},
{y:2020,c:"RePo",v:20,q:"The ____ program allows U.S. employers who meet specific regulatory requirements to bring foreign nationals to the United States to fill temporary agricultural jobs.",a:"H-2A"},
{y:2020,c:"RePo",v:25,q:"_____ is a permanent appropriation that since 1935 has set aside the equivalent of 30% of annual customs receipts to support the farm sector through the purchase of surplus commodities and other activities.",a:"Section 32"},
{y:2020,c:"Quant",v:5,q:"What is the shape of a distribution that has the mode equal to the median and mean?",a:"Symmetrical distribution"},
{y:2020,c:"Quant",v:10,q:"What is the result when a matrix is multiplied by its inverse?",a:"An identity matrix"},
{y:2020,c:"Quant",v:15,q:"If the mean is less than the median, then the distribution is ________ __________.",a:"Negatively skewed"},
{y:2020,c:"Quant",v:20,q:"In OLS, what is the common 'student' test to determine if an individual coefficient estimate is significantly different from zero?",a:"t-test"},
{y:2020,c:"Quant",v:25,q:"What statistic could be used to test whether two samples came from the same population?",a:"The t-statistic or the F-statistic"},
{y:2020,c:"Marketing",v:5,q:"The cash price offered at an elevator for immediate delivery is called what?",a:"Spot price"},
{y:2020,c:"Marketing",v:10,q:"The process of converting corn into ethanol adds ____ utility.",a:"Form"},
{y:2020,c:"Marketing",v:15,q:"The pricing policy where a firm sells a new product at a low price to increase market share at startup is called ______.",a:"Penetration pricing"},
{y:2020,c:"Marketing",v:20,q:"Name two of the three primary ways to price a product.",a:"Customer-based, competition-based, and cost-based (any two)"},
{y:2020,c:"Marketing",v:25,q:"____ is one of the four main risk measures used by options traders and measures the degree to which an option is exposed to shifts in the underlying futures price.",a:"Delta"},
{y:2020,c:"Management",v:5,q:"In this form of business organization, the owner owns and manages the business, assumes all risks, and receives all profit.",a:"Sole Proprietorship"},
{y:2020,c:"Management",v:10,q:"A management system within an organization that is '_____' has the advantage of clear procedures that are not influenced by external interactions.",a:"Closed"},
{y:2020,c:"Management",v:15,q:"When developing business objectives, objectives should be SMART. What does the acronym SMART stand for?",a:"Specific, Measurable, Attainable, Realistic, and Time-based"},
{y:2020,c:"Management",v:20,q:"Whose classic management theory developed the idea of management by objectives (MBO)?",a:"Peter Drucker"},
{y:2020,c:"Management",v:25,q:"What process is defined by making and implementing short-term decisions that keep the firm moving toward its long-term goals?",a:"Tactical Management"},
{y:2020,c:"Potpourri",v:5,q:"What is the motto of FFA?",a:"Learning to Do, Doing to Learn, Earning to Live, Living to Serve"},
{y:2020,c:"Potpourri",v:10,q:"'To make the best better' is the motto of what organization?",a:"4-H"},
{y:2020,c:"Potpourri",v:15,q:"Who was the first person to cultivate tobacco in Virginia (and was also the spouse of Pocahontas)?",a:"John Rolfe"},
{y:2020,c:"Potpourri",v:20,q:"The Hawaiian alphabet has how many letters?",a:"12"},
{y:2020,c:"Potpourri",v:25,q:"Name the highly contagious disease of cattle, goats, sheep, and swine that can be transmitted to humans (undulant fever).",a:"Brucellosis"},

/* ---------------- 2021 ---------------- */
{y:2021,c:"Micro",v:5,q:"A maximum price set by law is also called a price _____.",a:"Ceiling"},
{y:2021,c:"Micro",v:10,q:"The Latin phrase commonly used in economics for 'all other things being equal' is _____.",a:"Ceteris paribus"},
{y:2021,c:"Micro",v:15,q:"The cross-price elasticity between two substitutes is ____.",a:"Positive"},
{y:2021,c:"Micro",v:20,q:"If the inverse demand equation is P = 10 \u2212 2Q, what is the equation for the Marginal Revenue curve?",a:"MR = 10 \u2212 4Q"},
{y:2021,c:"Micro",v:25,q:"When the inputs used to produce output must be used in fixed proportions, what shape will the isoquant be?",a:"L-shaped (right angle)"},
{y:2021,c:"Macro",v:5,q:"FDIC is an abbreviation for what?",a:"Federal Deposit Insurance Corporation"},
{y:2021,c:"Macro",v:15,q:"If the Marginal Propensity to Consume (MPC) equals 0.84, what is the Marginal Propensity to Save?",a:"0.16 (MPS = 1 \u2212 MPC)"},
{y:2021,c:"Macro",v:20,q:"Subtracting depreciation from GDP yields what?",a:"Net Domestic Product"},
{y:2021,c:"Macro",v:25,q:"What happens to the net export curve if the government removes trade restrictions on imported goods?",a:"It shifts to the left (inward)"},
{y:2021,c:"Macro",v:10,q:"If the U.S. dollar appreciates, what has happened to the value of the U.S. dollar globally?",a:"It increased"},
{y:2021,c:"Finance",v:5,q:"What are total liabilities for a firm with $500,000 of equity and $750,000 of total assets?",a:"$250,000"},
{y:2021,c:"Finance",v:10,q:"What does the acronym EBITDA stand for?",a:"Earnings Before Interest, Tax, Depreciation, and Amortization"},
{y:2021,c:"Finance",v:15,q:"______________ is a series of uniform, periodic payments received (or paid) for either a fixed number of periods or in perpetuity.",a:"Annuity"},
{y:2021,c:"Finance",v:20,q:"John is conducting an analysis to determine how changes in the price of an output impact the proposed investment's net present value. This type of analysis is called what?",a:"Sensitivity analysis"},
{y:2021,c:"Finance",v:25,q:"Lenders typically are concerned about a firm's debt-to-equity ratio when it exceeds what value?",a:"1:1 (debt greater than equity)"},
{y:2021,c:"RePo",v:5,q:"The purpose of the _____ Act funding is to conduct research programs at state agricultural experiment stations.",a:"Hatch Act"},
{y:2021,c:"RePo",v:10,q:"____ _____ are defined as a farm's crop-specific acreage of wheat, feed grains, rice, oilseeds, pulse crops, or peanuts eligible for FSA program purposes.",a:"Base Acres"},
{y:2021,c:"RePo",v:15,q:"For the first food stamp program (1939), what were the two colors of the food stamps?",a:"Orange and blue"},
{y:2021,c:"RePo",v:20,q:"Which president requested Congress to pass legislation making the food stamp act permanent?",a:"Lyndon Johnson"},
{y:2021,c:"RePo",v:25,q:"President Abraham Lincoln called USDA the _________ department.",a:"People's"},
{y:2021,c:"Quant",v:5,q:"What is the sum of the interior angles of a triangle?",a:"180 degrees"},
{y:2021,c:"Quant",v:10,q:"For a function of a single variable x, what is the second-order condition for the function to have a maximum?",a:"The second-order condition must be negative at the maximum point"},
{y:2021,c:"Quant",v:15,q:"Suppose the short-run production function is q = 10L. If the wage rate is $10 per unit of labor, then the average variable cost equals what?",a:"1"},
{y:2021,c:"Quant",v:20,q:"OLS estimators are widely used because they are BLUE; what does BLUE stand for?",a:"Best Linear Unbiased Estimators"},
{y:2021,c:"Quant",v:25,q:"You throw two fair dice and observe the two faces up. What is the probability that the sum is not less than 4?",a:"1 \u2212 (3/36), i.e. 11/12"},
{y:2021,c:"Marketing",v:5,q:"This animal indicates rising futures prices.",a:"Bull"},
{y:2021,c:"Marketing",v:10,q:"This term is associated with a product priced at less than the seller's cost in hopes of attracting customers into the store who will then purchase more profitably priced merchandise.",a:"Loss leader"},
{y:2021,c:"Marketing",v:15,q:"An agricultural marketing firm that targets advertising to only farms within a 100-mile-diameter area is engaged in market ___________.",a:"Segmentation"},
{y:2021,c:"Marketing",v:20,q:"Craftsman tools sold by Sears is an example of a ___ brand.",a:"Family"},
{y:2021,c:"Marketing",v:25,q:"The Simpsons own a medium-sized farm. The family business stores all financial information in notebooks and has shunned computer use. In the product adoption curve, this makes them ______.",a:"Laggards"},
{y:2021,c:"Management",v:5,q:"What does the acronym SWOT stand for?",a:"Strengths, Weaknesses, Opportunities, and Threats"},
{y:2021,c:"Management",v:10,q:"In 1980, Michael Porter developed this model providing an excellent framework for analyzing industry competition.",a:"Porter's Five Forces Model"},
{y:2021,c:"Management",v:15,q:"Insurance, hedging, contracting, diversification, and financial reserves are all options for managing _______________.",a:"Risk"},
{y:2021,c:"Management",v:20,q:"A formal, written plan detailing how the firm will use its resources, what amount of sales is expected, and so on, during some future period is called what?",a:"Budget"},
{y:2021,c:"Management",v:25,q:"A written instrument by which one transfers his rights or interest in chattels and goods to another is called what?",a:"Bill of Sale"},
{y:2021,c:"Potpourri",v:5,q:"For what does the acronym 'TINSTAAFL' stand?",a:"There Is No Such Thing As A Free Lunch"},
{y:2021,c:"Potpourri",v:10,q:"What place is the Secretary of Agriculture in the line of succession?",a:"9th"},
{y:2021,c:"Potpourri",v:15,q:"Starting from the Declaration of Independence, how old was the USA in 2021?",a:"245 years (born 1776)"},
{y:2021,c:"Potpourri",v:20,q:"Thomas Malthus argued that living standards would fall because population was growing at a(n) ___________ rate, and food production would grow at a(n) ______________ rate.",a:"Geometric; arithmetic"},
{y:2021,c:"Potpourri",v:25,q:"Upton Sinclair's book 'The Jungle' led to a public outcry which caused the U.S. government to establish food safety procedures. What year was 'The Jungle' published?",a:"1906"},

/* ---------------- 2022 ---------------- */
{y:2022,c:"Micro",v:5,q:"If someone says 'the government ought to raise taxes on the wealthy,' this is a ______ statement.",a:"Normative"},
{y:2022,c:"Micro",v:10,q:"Consider the demand curve for an inferior good. If income rises, demand for the inferior good will shift ____.",a:"Left (down)"},
{y:2022,c:"Micro",v:20,q:"A single factory in a town is offering double the wage of other firms in order to attract the best potential employees. What type of wage are they offering?",a:"An efficiency wage"},
{y:2022,c:"Micro",v:25,q:"The _______ model of trade says that countries will export products that use their abundant factor of production and import products that use their scarce factors.",a:"Heckscher-Ohlin (H-O)"},
{y:2022,c:"Micro",v:15,q:"Average Product crosses Marginal Product at MP's ________. (From Round 3)",a:"Maximum of Average Product (MP crosses AP at AP's maximum)"},
{y:2022,c:"Macro",v:5,q:"During the downturn portion of a business cycle, the economy is characterized by what?",a:"Falling output and rising unemployment"},
{y:2022,c:"Macro",v:10,q:"The Quantity Theory of Money uses the equation MV = PQ and assumes which two variables are held constant?",a:"V and Q"},
{y:2022,c:"Macro",v:15,q:"What do we call the fractional change in disposable income that is spent on consumer goods?",a:"Marginal propensity to consume"},
{y:2022,c:"Macro",v:20,q:"What two variables are determined by the Mundell-Fleming Model?",a:"Nominal exchange rate and GDP"},
{y:2022,c:"Macro",v:25,q:"Cost-push inflation is caused by what economic change?",a:"Increases in the prices of inputs"},
{y:2022,c:"Finance",v:5,q:"This statement shows the annual flow and timing of cash into and out of a business.",a:"Cash Flow Statement"},
{y:2022,c:"Finance",v:10,q:"The net value that could be received from the best alternative use of a resource is called _____________.",a:"Opportunity Cost"},
{y:2022,c:"Finance",v:15,q:"Name the four major functions of management.",a:"Planning, Organizing, Directing, and Controlling"},
{y:2022,c:"Finance",v:20,q:"Net worth, the debt-to-asset ratio, and the leverage ratio are all measures of: efficiency, liquidity, repayment capacity, or solvency?",a:"Solvency"},
{y:2022,c:"Finance",v:25,q:"____________ is the number of years required to recover the initial cost of an investment.",a:"Payback Period"},
{y:2022,c:"RePo",v:5,q:"Often, agencies divide their responsibilities based on MOUs. The acronym MOU stands for what?",a:"Memorandum of Understanding"},
{y:2022,c:"RePo",v:10,q:"The 'hot coffee case' was between Stella Liebeck and which restaurant company?",a:"McDonald's"},
{y:2022,c:"RePo",v:15,q:"In debates regarding food additives, the acronym 'GRAS' stands for what?",a:"Generally Recognized As Safe"},
{y:2022,c:"RePo",v:20,q:"If you see a 'made with organic ingredients' label, the product must contain what minimum percent of certified organic ingredients?",a:"70%"},
{y:2022,c:"RePo",v:25,q:"The ____ _____ (Latin words) is a collection of internationally adopted food standards aimed at protecting consumer health and ensuring fair practices in food trade.",a:"Codex Alimentarius"},
{y:2022,c:"Quant",v:5,q:"The vertical distance between Total Revenue and Total Cost on a graph is _____.",a:"Profit"},
{y:2022,c:"Quant",v:10,q:"BLUE is the acronym for what phrase?",a:"Best Linear Unbiased Estimator"},
{y:2022,c:"Quant",v:15,q:"A(n) _____ variable is one whose cause is external to the model and whose role is to explain other variables or outcomes in the model.",a:"Exogenous"},
{y:2022,c:"Quant",v:20,q:"For a normal distribution with a mean of 100 and a standard deviation of 10, what percentage of the population can be expected to have a score higher than 120?",a:"2.5%"},
{y:2022,c:"Quant",v:25,q:"Given the demand equation P = 100 \u2212 2Q, what is the equation for marginal revenue?",a:"MR = 100 \u2212 4Q"},
{y:2022,c:"Marketing",v:5,q:"The value of a good associated with its availability in a form convenient to buyers is called ____________ utility.",a:"Form"},
{y:2022,c:"Marketing",v:10,q:"Hog prices rise, inducing producers to retain more of their gilts for breeding, thereby inducing further price rises. This is the ___________ phase of the hog price cycle.",a:"Expansion"},
{y:2022,c:"Marketing",v:15,q:"Approximately what percentage of all commodity futures contracts result in someone taking delivery of the actual commodity?",a:"About 3% (2% to 4% acceptable)"},
{y:2022,c:"Marketing",v:20,q:"The lobbying of government for preferential access to particular markets or tax advantages is referred to as what type of activity?",a:"Rent seeking"},
{y:2022,c:"Marketing",v:25,q:"What concept describes the series of steps by which consumers receive and use information in reaching decisions about what actions they will take (e.g., whether or not to buy a product)?",a:"Hierarchy-of-effects theory"},
{y:2022,c:"Management",v:5,q:"Define SWOT.",a:"Strengths, Weaknesses, Opportunities, and Threats"},
{y:2022,c:"Management",v:10,q:"__________________ is a management philosophy that strives to involve everyone in a continual effort to improve quality and achieve customer satisfaction.",a:"Total Quality Management (TQM)"},
{y:2022,c:"Management",v:15,q:"This is defined as the process of specifying an organization's objectives, developing policies and plans to achieve them, and allocating resources to implement the plans.",a:"Strategic Management"},
{y:2022,c:"Management",v:20,q:"What is the method by which cooperatives return 'profits' back to their members?",a:"Patronage Refund"},
{y:2022,c:"Management",v:25,q:"This is a diagram that traces out all the possible strategies and outcomes for a particular decision or sequence of related (usually risky) decisions.",a:"Decision Tree"},
{y:2022,c:"Potpourri",v:5,q:"How many NFL teams are located in California?",a:"3 (Rams, Chargers, 49ers)"},
{y:2022,c:"Potpourri",v:10,q:"Who is the only US president that served two non-consecutive terms (as of 2022)?",a:"Grover Cleveland"},
{y:2022,c:"Potpourri",v:15,q:"Who was the first US president to be impeached?",a:"Andrew Johnson"},
{y:2022,c:"Potpourri",v:20,q:"Woodrow Wilson had a pet ram. What was the name of the ram?",a:"Old Ike"},
{y:2022,c:"Potpourri",v:25,q:"Who was the first president born after the US Declaration of Independence?",a:"Martin Van Buren"},

/* ---------------- 2023 ---------------- */
{y:2023,c:"Micro",v:5,q:"If the input price is given at $1.50 per unit, and the output price is given at $2 per unit, what is the marginal revenue?",a:"$2 (the output price is the marginal revenue)"},
{y:2023,c:"Micro",v:10,q:"_________________________ is a response curve that shows the relationship between input and output.",a:"Production function"},
{y:2023,c:"Micro",v:15,q:"_________ is based on models of consumers or firms (agents) that make decisions about what to buy, sell, or produce, with the assumption that those decisions result in perfect market clearing.",a:"Microeconomics"},
{y:2023,c:"Micro",v:20,q:"A curve that depicts the maximum output possibility for two combination goods produced when resources are fixed at a given period of time is called what?",a:"Production Possibility Frontier"},
{y:2023,c:"Micro",v:25,q:"When a monopolist charges a different price depending on how much the consumer buys, what type of price discrimination is taking place?",a:"Second-degree price discrimination"},
{y:2023,c:"Macro",v:5,q:"David Ricardo, a British political economist, is best known for developing the ___________.",a:"Theory of comparative advantage"},
{y:2023,c:"Macro",v:10,q:"Real GDP refers to what?",a:"GDP data (sum of all monetary transactions involving final goods and services) that have been adjusted for changes in the price level"},
{y:2023,c:"Macro",v:15,q:"___________ is a comparison of the price of a market basket from a fixed point of reference.",a:"A price index"},
{y:2023,c:"Macro",v:20,q:"Who was the chairman of the Board of Governors of the Federal Reserve System in 2023?",a:"Jerome Powell"},
{y:2023,c:"Macro",v:25,q:"Joanna voluntarily quit her job as an insurance agent to return to school full-time to earn an MBA. With degree in hand she is now searching for a position in management. Joanna is presently ________________ unemployed.",a:"Frictionally unemployed"},
{y:2023,c:"Finance",v:5,q:"Arbitrage should eventually cause prices to _____.",a:"Converge"},
{y:2023,c:"Finance",v:10,q:"What is the mathematical process of calculating the present value of a known future value called?",a:"Discounting"},
{y:2023,c:"Finance",v:15,q:"How is working capital calculated?",a:"Current assets minus current liabilities"},
{y:2023,c:"Finance",v:20,q:"What is calculated as a ratio between net profit and cost of investment?",a:"Return on investment (ROI)"},
{y:2023,c:"Finance",v:25,q:"A capital budgeting method which computes the length of time required for the accumulated returns to equal the original investment is called what?",a:"Payback period (payback method)"},
{y:2023,c:"RePo",v:5,q:"What was the largest source of electricity globally in 2023?",a:"Coal"},
{y:2023,c:"RePo",v:10,q:"________ is the largest aquifer in the United States.",a:"Ogallala"},
{y:2023,c:"RePo",v:15,q:"_____________ sets standards and regulations for many different contaminants in public drinking water in the USA.",a:"The U.S. Environmental Protection Agency (EPA)"},
{y:2023,c:"RePo",v:20,q:"_______ helps producers, soil and water conservation districts, and other partners protect and conserve natural resources on private lands throughout the United States.",a:"NRCS (Natural Resources Conservation Service)"},
{y:2023,c:"RePo",v:25,q:"________________ is the world's largest conservation organization, with the mission 'to conserve nature and reduce the most pressing threats to the diversity of life on Earth.'",a:"WWF (World Wildlife Fund)"},
{y:2023,c:"Quant",v:5,q:"When there is only one mode, the distribution is called _________.",a:"Unimodal"},
{y:2023,c:"Quant",v:10,q:"What does the acronym ANOVA stand for?",a:"Analysis of Variance"},
{y:2023,c:"Quant",v:15,q:"Nominal variables with two classification levels are called _________________.",a:"Dichotomous variables"},
{y:2023,c:"Quant",v:20,q:"This assumption means that the variance around the regression line is the same for all values of the predictor variable (X).",a:"Homoscedasticity"},
{y:2023,c:"Quant",v:25,q:"You have committed a _________ error if you have rejected the hypothesis tested when it was true.",a:"Type I Error"},
{y:2023,c:"Marketing",v:5,q:"The direct exchange of goods and services between two parties, often without cash considerations, is called _________.",a:"Barter (bartering)"},
{y:2023,c:"Marketing",v:10,q:"What does GATT stand for?",a:"General Agreement on Tariffs and Trade"},
{y:2023,c:"Marketing",v:15,q:"This condition occurs when demand outstrips supply or costs escalate, effecting an upward change in prices.",a:"Inflation"},
{y:2023,c:"Marketing",v:20,q:"What is the percentage change in price received in response to a one percent increase (or decrease) in the quantity supplied?",a:"The product's price flexibility"},
{y:2023,c:"Marketing",v:25,q:"A mechanism used to avoid the risk of a decline in the future market of a commodity, usually by entering into futures markets, is called ____________.",a:"Hedging"},
{y:2023,c:"Management",v:5,q:"___________ is the active cooperation of firms within an industry to reduce output and raise prices in order to get around the normal economic law of supply and demand.",a:"Collusion"},
{y:2023,c:"Management",v:10,q:"The depth of an organization's culture is also known as ___________.",a:"Cultural intensity"},
{y:2023,c:"Management",v:15,q:"The Sarbanes-Oxley Act was designed to protect _________________________.",a:"Shareholders from the excesses and failed oversight of firms"},
{y:2023,c:"Management",v:20,q:"Shareholders in a(n) _________________ are liable only to the extent of their investment.",a:"Corporation"},
{y:2023,c:"Management",v:25,q:"Frederick Winslow Taylor's management theory, whereby workflows are analyzed to improve efficiency, is called ______.",a:"Scientific management"},
{y:2023,c:"Potpourri",v:5,q:"Samuel Tilden, Grover Cleveland, Al Gore, and Hillary Clinton share what distinction among U.S. presidential candidates?",a:"They won the popular vote but lost the electoral college vote"},
{y:2023,c:"Potpourri",v:10,q:"Which African country was formerly known as Abyssinia?",a:"Ethiopia"},
{y:2023,c:"Potpourri",v:15,q:"Which singer's real name is Stefani Joanne Angelina Germanotta?",a:"Lady Gaga"},
{y:2023,c:"Potpourri",v:20,q:"Where were the Declaration of Independence, the Constitution, and the Bill of Rights stored during World War II?",a:"Fort Knox"},
{y:2023,c:"Potpourri",v:25,q:"Which country consumes the most chocolate per capita?",a:"Switzerland"},

/* ---------------- 2024 ---------------- */
{y:2024,c:"Micro",v:5,q:"Which of the following terms best describes the elasticity facing a competitive firm: inelastic, perfectly inelastic, perfectly elastic, or elastic?",a:"Perfectly elastic"},
{y:2024,c:"Micro",v:25,q:"What is the reason the marginal cost curve eventually increases as output increases for the typical firm?",a:"The law of diminishing marginal returns"},
{y:2024,c:"Micro",v:10,q:"What is a cost that has already been made and cannot be recovered called?",a:"Sunk cost"},
{y:2024,c:"Micro",v:20,q:"If consumer income declines, then the demand for ________ goods will increase.",a:"Inferior"},
{y:2024,c:"Micro",v:15,q:"What term refers to a product that people consume more of as the price rises and vice versa, thereby violating the law of demand?",a:"Giffen good"},
{y:2024,c:"Macro",v:5,q:"What are consumer products that are not consumed or that yield utility over long periods of time (more than 3 years) known as?",a:"Durable goods"},
{y:2024,c:"Macro",v:10,q:"__________ occurs when the rate of inflation declines.",a:"Disinflation"},
{y:2024,c:"Macro",v:25,q:"What is the difference between disposable income and discretionary income?",a:"Disposable income is income left after taxes; discretionary income is net income left after all necessary expenses (rent, food, clothing, etc.) are paid"},
{y:2024,c:"Macro",v:15,q:"One purpose of money is to be the item we use to buy and sell things. What is this function of money called?",a:"Medium of exchange"},
{y:2024,c:"Macro",v:20,q:"A tax for which high-income taxpayers pay a smaller fraction of their income than do low-income taxpayers is known as a __________ tax.",a:"Regressive"},
{y:2024,c:"Finance",v:5,q:"__________ refers to how quickly and easily a financial asset can be converted into cash without losing significant value.",a:"Liquidity"},
{y:2024,c:"Finance",v:10,q:"When a bank tries to make a wide variety of loans to various kinds of borrowers, it is hoping to reap the benefit of __________.",a:"Diversification"},
{y:2024,c:"Finance",v:15,q:"When a bank's credit analysis focuses on the assets offered by the loan applicant as security for a loan, which of the 'Five Cs' is being assessed?",a:"Collateral"},
{y:2024,c:"Finance",v:20,q:"A call option exists on Macroswift stock. The exercise price is $45; the call can be purchased for $7; the stock currently sells for $50 per share. What is the intrinsic value of the call option?",a:"$5"},
{y:2024,c:"Finance",v:25,q:"A/an ________ will pay a beneficiary a fixed amount, periodically, over some specified period of time.",a:"Annuity"},
{y:2024,c:"RePo",v:5,q:"What term refers to a user of a public good who does not contribute to its provision?",a:"Free rider"},
{y:2024,c:"RePo",v:10,q:"When an additional unit of output is produced, what is the extra cost to society referred to as?",a:"Marginal social cost (MSC)"},
{y:2024,c:"RePo",v:15,q:"What type of legislation is designed to make it illegal for a firm to monopolize an industry?",a:"Antitrust"},
{y:2024,c:"RePo",v:25,q:"What kind of resources lead to market failure because they are overexploited and under-supplied?",a:"Common property resources"},
{y:2024,c:"RePo",v:20,q:"What is said to occur when the allocation of a good or service by the free market is inefficient?",a:"Market failure"},
{y:2024,c:"Quant",v:5,q:"Suppose a 50% increase in the price of a drug results in no change in the quantity demanded. What is the price elasticity of the drug?",a:"0"},
{y:2024,c:"Quant",v:10,q:"If Jack received a $1,000 bonus and his marginal propensity to save is 0.15, his consumption rises by ________ and his saving rises by ________.",a:"$850; $150"},
{y:2024,c:"Quant",v:15,q:"The economy has an annual inflation rate of 3.5%. Approximately how many years will it take for the price level to double?",a:"About 20 years (Rule of 72)"},
{y:2024,c:"Quant",v:20,q:"A single-price monopoly can sell 10 units at $45 each, but to sell 11 units it must cut the price to $44. What is the marginal revenue of the extra unit sold?",a:"$34"},
{y:2024,c:"Quant",v:25,q:"The equation MP = b + 2cV \u2212 3dV\u00b2 was derived from a ________ production function.",a:"Cubic"},
{y:2024,c:"Marketing",v:5,q:"What is the time a product can be stored before it spoils called?",a:"Shelf life"},
{y:2024,c:"Marketing",v:10,q:"What historical event led to the creation of the field of macroeconomics?",a:"The Great Depression"},
{y:2024,c:"Marketing",v:15,q:"'The Paradox of Thrift,' as proposed by John Maynard Keynes, proposes that people doing what can actually be bad for the economy?",a:"Saving money"},
{y:2024,c:"Marketing",v:20,q:"When Tata Steel notices a drop in the demand for steel as a result of a decline in ultimate consumer demand for automobiles, this illustrates what concept?",a:"Derived demand"},
{y:2024,c:"Marketing",v:25,q:"What is a technique that uses a bright light to examine the inside of an egg?",a:"Candling"},
{y:2024,c:"Management",v:5,q:"What are accepted principles of right or wrong governing the conduct of businesspeople called?",a:"Business ethics"},
{y:2024,c:"Management",v:10,q:"What term describes an organization where top management delegates authority and responsibilities to lower levels of management and employees?",a:"Decentralized"},
{y:2024,c:"Management",v:15,q:"Individuals who make meaningful changes in the activities and architecture of the organization are known as _______________ leaders.",a:"Transformational"},
{y:2024,c:"Management",v:20,q:"When a firm makes decisions that assist it in formulating and implementing plans designed to achieve its objectives, it is most likely engaging in _________ management.",a:"Strategic"},
{y:2024,c:"Management",v:25,q:"The theory that explains how people develop perceptions of fairness in the distribution and exchange of resources is called ______ theory.",a:"Equity theory"},
{y:2024,c:"Potpourri",v:5,q:"Louisiana is the only U.S. state with political subdivisions termed ________, which are equivalent to counties.",a:"Parishes"},
{y:2024,c:"Potpourri",v:10,q:"Which of the following is likely to be the price elasticity of demand for food: 5.2, 2.6, 1.8, or 0.3?",a:"0.3"},
{y:2024,c:"Potpourri",v:15,q:"Which U.S. state produces the most rice?",a:"Arkansas"},
{y:2024,c:"Potpourri",v:20,q:"What firm became the world's most valuable company in 2024 in terms of market capitalization, thanks to a frenzy over the potential of its high-end processors for use in artificial intelligence?",a:"Nvidia Corporation"},
{y:2024,c:"Potpourri",v:25,q:"What U.S. city has become known as the 'Hollywood of the South' for its many television and movie productions?",a:"Atlanta"},

/* ---------------- 2025 ---------------- */
{y:2025,c:"Micro",v:5,q:"What happens to the level of output as the input combinations change along a production isoquant?",a:"Output remains unchanged"},
{y:2025,c:"Micro",v:10,q:"A production function represents the relationship between the maximum amount of ________ that can be produced with a given amount of ___________.",a:"Output; input"},
{y:2025,c:"Micro",v:15,q:"What is the term used for a market with a single buyer?",a:"Monopsony"},
{y:2025,c:"Micro",v:20,q:"In a perfectly competitive market, what can be said about the demand curve facing an individual seller?",a:"It is perfectly elastic (horizontal)"},
{y:2025,c:"Micro",v:25,q:"Given constant input prices, what connects the set of optimal input combinations as total input expenditures increase?",a:"The expansion path"},
{y:2025,c:"Macro",v:5,q:"The primary responsibility for US monetary policy is assigned to whom?",a:"The Federal Reserve"},
{y:2025,c:"Macro",v:10,q:"The dollar value of all finished goods and services produced within the economy in a given period of time is called what?",a:"Gross Domestic Product (GDP)"},
{y:2025,c:"Macro",v:15,q:"What method of measuring GDP totals all labor and other resource earnings within the economy during an accounting period?",a:"Income method"},
{y:2025,c:"Macro",v:20,q:"In an inflationary period, what is the expected relationship between nominal and real GDP?",a:"Nominal GDP exceeds real GDP"},
{y:2025,c:"Macro",v:25,q:"Which economic model illustrates the interaction between households, firms, the government, and the foreign sector?",a:"Circular flow model"},
{y:2025,c:"Finance",v:5,q:"The phrase 'a dollar today is worth more than a dollar next year' expresses what financial concept?",a:"Time value of money"},
{y:2025,c:"Finance",v:10,q:"What are the three primary forms of business organization?",a:"Sole proprietorship, partnership, corporation"},
{y:2025,c:"Finance",v:15,q:"What is meant by volume discount pricing?",a:"A reduction in the price per unit as the amount purchased increases"},
{y:2025,c:"Finance",v:20,q:"What are the four functions of management?",a:"Planning, Organizing, Controlling, Directing"},
{y:2025,c:"Finance",v:25,q:"If you borrow $100 and repay it over one year with 12 equal monthly payments of $10, what is the approximate annual percentage rate (APR) of the loan?",a:"About 40%"},
{y:2025,c:"RePo",v:5,q:"What is someone who benefits from a public good or service without paying any of the cost called?",a:"Free rider"},
{y:2025,c:"RePo",v:10,q:"Government payments to farmers for using environmentally friendly practices are commonly called what?",a:"'Green' payments"},
{y:2025,c:"RePo",v:15,q:"A restriction on the quantity of a good that a country allows to be imported is called what?",a:"A quota"},
{y:2025,c:"RePo",v:20,q:"What term is often used to describe the separation of government payments from market prices and production decisions?",a:"Decoupling"},
{y:2025,c:"RePo",v:25,q:"What type of price support loan exists when the producer has the right to forfeit the commodity rather than pay back the loan?",a:"Nonrecourse loan"},
{y:2025,c:"Quant",v:5,q:"The middle value in a set of observations is called what?",a:"The median"},
{y:2025,c:"Quant",v:10,q:"For an index number series, what is the value for the base year?",a:"100"},
{y:2025,c:"Quant",v:15,q:"What is the measure of dispersion calculated by summing each observation's squared deviation from the mean and dividing by n \u2212 1?",a:"Variance"},
{y:2025,c:"Quant",v:20,q:"What is the probability of rolling a six with a standard six-sided die?",a:"1/6 (about 16.67%)"},
{y:2025,c:"Quant",v:25,q:"What are the three common measures of central tendency?",a:"Mean, median, mode"},
{y:2025,c:"Marketing",v:5,q:"A union of two firms operating in totally unrelated markets represents what type of merger?",a:"Conglomerate merger"},
{y:2025,c:"Marketing",v:10,q:"A market where transactions occur for the purchase or sale of the physical commodity for immediate or deferred delivery is called what?",a:"A cash market"},
{y:2025,c:"Marketing",v:20,q:"If the strike price of a put option exceeds the underlying futures price, the put is said to be what?",a:"In-the-money"},
{y:2025,c:"Marketing",v:25,q:"What are the four types of utility created by the food marketing system?",a:"Form, time, place, and possession (ownership)"},
{y:2025,c:"Marketing",v:15,q:"A market with many sellers of a highly differentiated product is called what?",a:"Monopolistic competition"},
{y:2025,c:"Management",v:5,q:"What are the four basic functions of management?",a:"Planning, Organizing, Leading (Directing), Controlling"},
{y:2025,c:"Management",v:10,q:"Which leadership style involves leaders making all major decisions with little input from employees?",a:"Autocratic leadership"},
{y:2025,c:"Management",v:15,q:"In strategic planning, what term describes a statement that defines an organization's long-term aspirations and purpose?",a:"Vision Statement"},
{y:2025,c:"Management",v:25,q:"What does the acronym TQM stand for?",a:"Total Quality Management"},
{y:2025,c:"Management",v:20,q:"Which function of management involves monitoring performance and taking corrective action?",a:"Controlling"},
{y:2025,c:"Potpourri",v:5,q:"What type of utility is added to a commodity through the processing function?",a:"Form utility"},
{y:2025,c:"Potpourri",v:10,q:"Where does fertilization occur in a cow?",a:"The oviduct"},
{y:2025,c:"Potpourri",v:15,q:"Who was the author of 'An Inquiry into the Nature and Causes of the Wealth of Nations'?",a:"Adam Smith"},
{y:2025,c:"Potpourri",v:20,q:"Denver was founded during which historic event?",a:"The Pikes Peak Gold Rush (1858)"},
{y:2025,c:"Potpourri",v:25,q:"__________ __________ is the right reserved by the government to take private property.",a:"Eminent domain"}
];
